### ISSUE TITLE
Concurrent Modification Exception (plugin not working properly)

### ISSUE THREAD

**Issue by mjallen729** [Its-404/PerWorldChat#1]
I'm getting a concurrent modification exception on paper 1.16.3, plugin also not working properly when the error occurs (frequently).

The error:
```
[22:15:18 ERROR]: Could not pass event AsyncPlayerChatEvent to PerWorldChat vXII
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_251]
        at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_251]
        at me.four04.perworldchat.listeners.AsyncPlayerChat.onPlayerChat(AsyncPlayerChat.java:41) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-246]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.3.jar:git-Paper-246]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-246]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.PlayerConnection.chat(PlayerConnection.java:1831) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1746) ~[patched_1.16.3.jar:git-Paper-246]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.3.jar:git-Paper-246]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
```

> AsyncPlayerChat.onPlayerChat(AsyncPlayerChat.java:41)

**Comment by mjallen729** [comment]
I suspect the error is occurring here, specifically on "recipients.remove(recipient);".
```
for (Player recipient : recipients) {
  World world = recipient.getWorld();
  if (this.altDimensionDetected(origin.getName(), world.getName())) 
    continue;
  
  if (!world.equals(origin) && !linkedWorlds.contains(world)) {
    recipients.remove(recipient);
  }
}
```
Line 41 is the start of that for-each loop.

You're attempting to concurrently modify a list while its iterator is running. This will throw an exception. To get around this, I suggest the following:
```
Set<Player> tempRecipients = new HashSet<Player>(); //create temporary set for iteration purposes
tempRecipients.addAll(recipients); //copy existing recipients set to temp set

for (Player recipient : tempRecipients) { //iterate thru temporary set
  World world = recipient.getWorld();

  if (this.altDimensionDetected(origin.getName(), world.getName())) 
    continue;
  
  if (!world.equals(origin) && !linkedWorlds.contains(world)) {
    recipients.remove(recipient); //remove the recipient from the existing set, leaving temp iterating set unchanged.

  }
}
```

**Comment by mjallen729** [comment]
Fixed errors/bugs and pushed to my fork of the project.
